pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests install' 
            }
        }
        stage('Unit Test') { 
            steps {
                sh 'mvn clean test'  
            }
        }
        stage('Package') { 
            steps {
                sh 'mvn clean package'  
            }
        }
        stage('Create Image') { 
            steps {
                sh 'docker build -t boiaz/gameoflife:latest /home/boiaz/gameoflife/gameoflife-web'  
            }
        }
        stage('Push Image Image') { 
            steps {
                sh 'docker push boiaz/gameoflife:latest'  
            }
        }
        stage('Start Acceptance Environment') { 
            steps {
                sh 'ansible-playbook -vvv /etc/ansible/ec2-basic.yml'  
        stage('assign static IP') {
            steps {
                sh 'ansible-playbook -vvv /etc/ansible/ec2-staticip.yml'
            }
        } 
        stage('functionality test') { 
            steps {
                sh 'java -jar /home/boiaz/Documents/goltest.jar'  
            }
        }
        stage('terminate acceptance area') { 
            steps {
                sh 'ansible-playbook /etc/ansible/ec2-terminate.yml'  
            }
        }                    
    }
}
