pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean install' 
            }
        }
        stage('Unit Test') { 
            steps {
                sh 'mvn clean test'  
            }
        }
        stage('Package') { 
            steps {
                sh 'mvn clean package'  
            }
        }
        stage('Create Image') { 
            steps {
                sh 'docker build -t boiaz/gameoflife:latest'  
            }
        }
        stage('Push Image Image') { 
            steps {
                sh 'docker push boiaz/gameoflife:latest'  
            }
        }                  
    }
}
