pipeline {
    agent any
    stages {
        stage('Unit Test') { 
            steps {
                sh 'mvn clean test'  
            }
        }
        stage('Build') { 
            steps {
                sh 'mvn -DskipTests clean package'  
            }
        }
        stage('Create Image') { 
            steps {
                sh 'docker build -t boiaz/gameoflife:latest /home/boiaz/gameoflife/gameoflife-web'  
            }
        }
        stage('Push Image Image') { 
            steps {
                sh 'docker push boiaz/gameoflife:latest'  
            }
        }
        stage('Acceptance Environment') { 
            steps {
                sh 'ansible-playbook /etc/ansible/ec2-basic.yml'  
            }
        }
        stage('Functionality Test') {
            steps {
                sh 'java -jar /home/boiaz/Documents/goltest.jar'
            }
        }
        stage('Terminate Instance') {
            steps {
                sh 'ansible-playbook /etc/ansible/ec2-terminate.yml'
            }
        }
        stage('push to production') { 
            steps {
                sh 'ansible-playbook /etc/ansible/ec2-production.yml'  
            }
        }                    
    }
}
